version: 1
teams:
  A:
  - gitlab-org/gitlab
  - gitlab-org/gitlab-runner
  - gitlab-org/gitaly
  - gitlab-org/omnibus-gitlab
  - kernel
  - apache/airflow
  - eclipse_platform
  - z_archived
  - thunderbird
  - firefox_os_graveyard
  - mailnews_core
  - core_graveyard
  - add_on_sdk_graveyard
  - addons_mozilla_org_graveyard
  - air_mozilla
  - amp_archived
  - andmore
  - apogy_archived
  - aus_graveyard
  - b2gdroid_graveyard
  - b612
  - bugzilla
  - bugzilla_mozilla_org_graveyard
  - cck_graveyard
  - conduit
  - context_graph_graveyard
  - crash_pings
  - dali_jpa_tools
  - dash
  - data_bi_services_team_graveyard
  - data_platform_and_tools
  - data_science
  - dawnsci
  - derivatives_graveyard
  - developer_ecosystem
  - developer_engagement
  - developer_infrastructure
  - developer_mozilla_org
  - ditto
  - dltk
  - documentation_graveyard
  - e4
  - eclemma
  - ecp
  - egit
  - eliot
  - elk
  - elogbook
  - emf_diffmerge
  - emf_egf
  - emf_services
  - etrice
  - external_software_affecting_firefox
  - firefox_for_ios
  - firefox_health_report_graveyard
  - firefox_private_network
  - gemini_management
  - gemini_web
  - geobench
  - geomesa
  - geowave
  - gmf_runtime
  - gmf_tooling_archived
  - gmp
  - grendel_graveyard
  - handly
  - hawk
  - hello_loop
  - incubator
  - infrastructure_operations
  - intellego_graveyard
  - jakartaee_stable
  - jakartaee_tck
  - java_server_faces
  - jdt
  - jersey
  - jifa
  - kura
  - linux_tools
  - lockwise_graveyard
  - m2t
  - marketing
  - mat
  - mdt
  - mdt_rmf
  - microprofile
  - mihini
  - minimo_graveyard
  - mmt_atl
  - mozilla_foundation
  - mozilla_foundation_communications
  - mozilla_localizations
  - mozilla_localizations_graveyard
  - mozilla_messaging_graveyard
  - mozilla_reps_graveyard
  - mozillaclassic_graveyard
  - mozillaignite_graveyard
  - mozreview_graveyard
  - nattable
  - nebula_incubator
  - nss
  - oomph
  - openj9
  - openpass
  - orion_archived
  - osbp
  - osee
  - other_applications_graveyard
  - pancake_graveyard
  - papyrus
  - papyrus_rt
  - participation_infrastructure_graveyard
  - penelope_graveyard
  - platform
  - powertool_graveyard
  - product_innovation
  - ptp
  - release_engineering
  - release_engineering_graveyard
  - rhino_graveyard
  - rover
  - rtsc_archived
  - sfcurve
  - simultaneous_release
  - sirius
  - snippets
  - taskcluster
  - taskcluster_graveyard
  - tcf
  - tech_evangelism_graveyard
  - technology_top_level
  - tecken
  - tracecompass
  - tracecompass_incubator
  - unide_archived
  - upr_archived
  - user_experience_design_graveyard
  - ux_systems
  - virgo
  - websites
  - working_groups
  - wtp_common_tools
  - wtp_releng
  - www_mozilla_org
  - www_mozilla_org_graveyard
  - xacc
  - xwt
  B:
  - microsoft/vscode
  - llvm/llvm-project
  - nodejs/node
  - moby/moby
  - freebsd
  - firefox
  - seamonkey
  - toolkit
  - devtools
  - testing
  - firefox_for_android_graveyard
  - acceleo
  - addons_mozilla_org
  - agail
  - air_mozilla_graveyard
  - app4mc
  - application_services
  - aspectj
  - bugzilla_mozilla_org
  - buildship
  - camino_graveyard
  - chat_core
  - che
  - cloud_services
  - cloud_services_graveyard
  - community
  - cyclonedds
  - data_compliance
  - data_platform_and_tools_graveyard
  - developer_documentation_graveyard
  - developer_mozilla_org_graveyard
  - developer_services
  - devtools_graveyard
  - directory_graveyard
  - dirigible
  - drupal
  - ecf
  - eef
  - efm
  - efxclipse
  - ejb
  - emerging_markets_graveyard
  - emf_parsley
  - emfstore
  - emft
  - emft_doc2model
  - enterprise_information_security_graveyard
  - epp
  - esf
  - extend_firefox_graveyard
  - external_software_affecting_firefox_graveyard
  - fenix_graveyard
  - firefox_build_system
  - firefox_for_echo_show_graveyard
  - firefox_for_firetv_graveyard
  - firefox_friends_graveyard
  - firefox_graveyard
  - focus
  - focus_ios
  - geckoview_graveyard
  - gef
  - gemini_dbaccess
  - gemini_jpa
  - gemini_naming
  - gendoc
  - general
  - growth
  - ice
  - infrastructure_operations_graveyard
  - input
  - iofog
  - jgit
  - jts
  - jubula_archived
  - justj
  - kapua
  - kuksa
  - l20n_graveyard
  - libims
  - localization_infrastructure_and_tools
  - location
  - lyo
  - mailnews_core_graveyard
  - mangrove_archived
  - marketplace_graveyard
  - mdht
  - mdt_bpmn2
  - milo
  - mozilla_labs
  - mozilla_labs_graveyard
  - mozilla_org_graveyard
  - mtj_archived
  - objectteams
  - ocl
  - orbit
  - other_applications
  - pde
  - plugins_graveyard
  - pmf
  - pocket
  - privacy_graveyard
  - qvtd
  - reqcycle
  - rest
  - rich_beans
  - servo_graveyard
  - shield
  - skills_archived
  - soa_platform
  - spatial4j
  - sphinx
  - statet
  - stem
  - subversive
  - support_mozilla_org_graveyard
  - support_mozilla_org_lithium
  - support_mozillamessaging_com_graveyard
  - swtbot
  - swtchart
  - tea
  - testing_graveyard
  - testopia
  - tmf
  - toolkit_graveyard
  - tools
  - tracking_graveyard
  - user_research
  - vertx
  - viatra
  - vorto
  - vtp
  - web_apps
  - web_apps_graveyard
  - web_compatibility
  - webmaker_graveyard
  - websites_graveyard
  - webtools_graveyard
  - woolsey
  - wtp_ejb_tools
  - wtp_java_ee_tools
  - wtp_webservices
  - wtp_website
  - www_firefox_com
  - xpect
  C:
  - rust-lang/rust
  - python/cpython
  - kubernetes/kubernetes
  - gcc
  - libreoffice
  - core
  - cdt
  - calendar
  - firefox_for_android
  - invalid_bugs
  - equinox
  - 4diac
  - ajdt
  - amalgam
  - android_background_services_graveyard
  - babel
  - basyx
  - boot2gecko_graveyard
  - bpmn2modeler
  - ca_program
  - californium
  - camf_archived
  - capella
  - capra
  - cbi
  - cft
  - chemclipse
  - cognicrypt
  - community_building
  - composer_graveyard
  - conduit_graveyard
  - connected_devices_graveyard
  - content_services_graveyard
  - data_bi_services_team
  - data_tools
  - datazilla_graveyard
  - deeplearning4j
  - developer_engagement_graveyard
  - doh_trr_program
  - ease
  - eavp
  - ecoretools
  - edapt
  - egerrit
  - emf
  - emfcompare
  - emft_henshin
  - emft_refactor
  - epsilon
  - firefox_affiliates_graveyard
  - firefox_enterprise
  - firefox_for_metro_graveyard
  - firefox_profiler
  - fsa_graveyard
  - geckoview
  - gemini
  - gemini_blueprint
  - geogig
  - geotrellis
  - graphiti
  - hawkbit
  - hudson
  - input_graveyard
  - instantbird_graveyard
  - instantbird_servers_graveyard
  - internet_public_policy
  - jetty
  - jsdt
  - jss_graveyard
  - jwt_archived
  - keti
  - kitalpha
  - l20n
  - ldt
  - localization_infrastructure_and_tools_graveyard
  - m2e_wtp
  - marketing_graveyard
  - mdmbl
  - mdmweb
  - mdt_uml2
  - mmt
  - modeling
  - modisco
  - mozilla_china
  - mozilla_metrics
  - mozilla_org
  - mozilla_qa
  - mozilla_qa_graveyard
  - mozilla_reps
  - mozilla_vpn
  - mpc
  - nspr
  - ogee_archived
  - om2m
  - omr
  - openk_usermodules
  - packager
  - paho
  - participation_infrastructure
  - passage
  - pdt_incubator
  - petri_graveyard
  - plugin_check_graveyard
  - quality_mozilla_org
  - qvto
  - rap
  - rcptt
  - reddeer
  - release_management
  - remote_protocol
  - riena
  - security_assurance
  - sisu
  - skywriter_graveyard
  - snippets_graveyard
  - socorro
  - socorro_graveyard
  - support_mozilla_org
  - sw360
  - tamarin_graveyard
  - target_management
  - texlipse
  - tigerstripe_archived
  - time4sys
  - titan
  - tracking
  - tree_management
  - tree_management_graveyard
  - udig
  - uomo
  - usssdk
  - wakaama
  - web_tools
  - webextensions
  - webtools
  - wtp_servertools
  - wtp_source_editing
  - xtend
