version: 1
teams:
  A:
  - gitlab-org/gitlab
  - gitlab-org/gitlab-runner
  - gitlab-org/gitaly
  - gitlab-org/omnibus-gitlab
  - kernel
  - apache/airflow
  - eclipse_platform
  - z_archived
  - thunderbird
  - firefox_os_graveyard
  - mailnews_core
  - core_graveyard
  - add_on_sdk_graveyard
  - addons_mozilla_org_graveyard
  - air_mozilla
  - amp_archived
  - andmore
  - apogy_archived
  - aus_graveyard
  - b2gdroid_graveyard
  - b612
  - bugzilla
  - bugzilla_mozilla_org_graveyard
  - cck_graveyard
  - conduit
  - context_graph_graveyard
  - crash_pings
  - dali_jpa_tools
  - dash
  - data_bi_services_team_graveyard
  - data_platform_and_tools
  - data_science
  - dawnsci
  - derivatives_graveyard
  - developer_ecosystem
  - developer_engagement
  - developer_infrastructure
  - developer_mozilla_org
  - ditto
  - dltk
  - documentation_graveyard
  - e4
  - eclemma
  - ecp
  - egit
  - eliot
  - elk
  - elogbook
  - emf_diffmerge
  - emf_egf
  - emf_services
  - etrice
  - external_software_affecting_firefox
  - firefox_for_ios
  - firefox_health_report_graveyard
  - firefox_private_network
  - gemini_management
  - gemini_web
  - geobench
  - geomesa
  - geowave
  - gmf_runtime
  - gmf_tooling_archived
  - gmp
  - grendel_graveyard
  - handly
  - hawk
  - hello_loop
  - incubator
  - infrastructure_operations
  - intellego_graveyard
  - jakartaee_stable
  - jakartaee_tck
  - java_server_faces
  - jdt
  - jersey
  - jifa
  - kura
  - linux_tools
  - lockwise_graveyard
  - m2t
  - marketing
  - mat
  - mdt
  - mdt_rmf
  - microprofile
  - mihini
  - minimo_graveyard
  - mmt_atl
  - mozilla_foundation
  - mozilla_foundation_communications
  - mozilla_localizations
  - mozilla_localizations_graveyard
  - mozilla_messaging_graveyard
  - mozilla_reps_graveyard
  - mozillaclassic_graveyard
  - mozillaignite_graveyard
  - mozreview_graveyard
  - nattable
  - nebula_incubator
  - nss
  - oomph
  - openj9
  - openpass
  - orion_archived
  - osbp
  - osee
  - other_applications_graveyard
  - pancake_graveyard
  - papyrus
  - papyrus_rt
  - participation_infrastructure_graveyard
  - penelope_graveyard
  - platform
  - powertool_graveyard
  - product_innovation
  - ptp
  - release_engineering
  - release_engineering_graveyard
  - rhino_graveyard
  - rover
  - rtsc_archived
  - sfcurve
  - simultaneous_release
  - sirius
  - snippets
  - taskcluster
  - taskcluster_graveyard
  - tcf
  - tech_evangelism_graveyard
  - technology_top_level
  - tecken
  - tracecompass
  - tracecompass_incubator
  - unide_archived
  - upr_archived
  - user_experience_design_graveyard
  - ux_systems
  - virgo
  - websites
  - working_groups
  - wtp_common_tools
  - wtp_releng
  - www_mozilla_org
  - www_mozilla_org_graveyard
  - xacc
  - xwt
  B:
  - microsoft/vscode
  - llvm/llvm-project
  - nodejs/node
  - moby/moby
  - freebsd
  - firefox
  - seamonkey
  - toolkit
  - devtools
  - testing
  - firefox_for_android_graveyard
  - acceleo
  - addons_mozilla_org
  - agail
  - air_mozilla_graveyard
  - app4mc
  - application_services
  - aspectj
  - bugzilla_mozilla_org
  - buildship
  - camino_graveyard
  - chat_core
  - che
  - cloud_services
  - cloud_services_graveyard
  - community
  - cyclonedds
  - data_compliance
  - data_platform_and_tools_graveyard
  - developer_documentation_graveyard
  - developer_mozilla_org_graveyard
  - developer_services
  - devtools_graveyard
  - directory_graveyard
  - dirigible
  - drupal
  - ecf
  - eef
  - efm
  - efxclipse
  - ejb
  - emerging_markets_graveyard
  - emf_parsley
  - emfstore
  - emft
  - emft_doc2model
  - enterprise_information_security_graveyard
  - epp
  - esf
  - extend_firefox_graveyard
  - external_software_affecting_firefox_graveyard
  - fenix_graveyard
  - firefox_build_system
  - firefox_for_echo_show_graveyard
  - firefox_for_firetv_graveyard
  - firefox_friends_graveyard
  - firefox_graveyard
  - focus
  - focus_ios
  - geckoview_graveyard
  - gef
  - gemini_dbaccess
  - gemini_jpa
  - gemini_naming
  - gendoc
  - general
  - growth
  - ice
  - infrastructure_operations_graveyard
  - input
  - iofog
  - jgit
  - jts
  - jubula_archived
  - justj
  - kapua
  - kuksa
  - l20n_graveyard
  - libims
  - localization_infrastructure_and_tools
  - location
  - lyo
  - mailnews_core_graveyard
  - mangrove_archived
  - marketplace_graveyard
  - mdht
  - mdt_bpmn2
  - milo
  - mozilla_labs
  - mozilla_labs_graveyard
  - mozilla_org_graveyard
  - mtj_archived
  - objectteams
  - ocl
  - orbit
  - other_applications
  - pde
  - plugins_graveyard
  - pmf
  - pocket
  - privacy_graveyard
  - qvtd
  - reqcycle
  - rest
  - rich_beans
  - servo_graveyard
  - shield
  - skills_archived
  - soa_platform
  - spatial4j
  - sphinx
  - statet
  - stem
  - subversive
  - support_mozilla_org_graveyard
  - support_mozilla_org_lithium
  - support_mozillamessaging_com_graveyard
  - swtbot
  - swtchart
  - tea
  - testing_graveyard
  - testopia
  - tmf
  - toolkit_graveyard
  - tools
  - tracking_graveyard
  - user_research
  - vertx
  - viatra
  - vorto
  - vtp
  - web_apps
  - web_apps_graveyard
  - web_compatibility
  - webmaker_graveyard
  - websites_graveyard
  - webtools_graveyard
  - woolsey
  - wtp_ejb_tools
  - wtp_java_ee_tools
  - wtp_webservices
  - wtp_website
  - www_firefox_com
  - xpect
  C:
  - rust-lang/rust
  - python/cpython
  - kubernetes/kubernetes
  - gcc
  - libreoffice
  - core
  - cdt
  - calendar
  - firefox_for_android
  - invalid_bugs
  - equinox
  - 4diac
  - ajdt
  - amalgam
  - android_background_services_graveyard
  - babel
  - basyx
  - boot2gecko_graveyard
  - bpmn2modeler
  - ca_program
  - californium
  - camf_archived
  - capella
  - capra
  - cbi
  - cft
  - chemclipse
  - cognicrypt
  - community_building
  - composer_graveyard
  - conduit_graveyard
  - connected_devices_graveyard
  - content_services_graveyard
  - data_bi_services_team
  - data_tools
  - datazilla_graveyard
  - deeplearning4j
  - developer_engagement_graveyard
  - doh_trr_program
  - ease
  - eavp
  - ecoretools
  - edapt
  - egerrit
  - emf
  - emfcompare
  - emft_henshin
  - emft_refactor
  - epsilon
  - firefox_affiliates_graveyard
  - firefox_enterprise
  - firefox_for_metro_graveyard
  - firefox_profiler
  - fsa_graveyard
  - geckoview
  - gemini
  - gemini_blueprint
  - geogig
  - geotrellis
  - graphiti
  - hawkbit
  - hudson
  - input_graveyard
  - instantbird_graveyard
  - instantbird_servers_graveyard
  - internet_public_policy
  - jetty
  - jsdt
  - jss_graveyard
  - jwt_archived
  - keti
  - kitalpha
  - l20n
  - ldt
  - localization_infrastructure_and_tools_graveyard
  - m2e_wtp
  - marketing_graveyard
  - mdmbl
  - mdmweb
  - mdt_uml2
  - mmt
  - modeling
  - modisco
  - mozilla_china
  - mozilla_metrics
  - mozilla_org
  - mozilla_qa
  - mozilla_qa_graveyard
  - mozilla_reps
  - mozilla_vpn
  - mpc
  - nspr
  - ogee_archived
  - om2m
  - omr
  - openk_usermodules
  - packager
  - paho
  - participation_infrastructure
  - passage
  - pdt_incubator
  - petri_graveyard
  - plugin_check_graveyard
  - quality_mozilla_org
  - qvto
  - rap
  - rcptt
  - reddeer
  - release_management
  - remote_protocol
  - riena
  - security_assurance
  - sisu
  - skywriter_graveyard
  - snippets_graveyard
  - socorro
  - socorro_graveyard
  - support_mozilla_org
  - sw360
  - tamarin_graveyard
  - target_management
  - texlipse
  - tigerstripe_archived
  - time4sys
  - titan
  - tracking
  - tree_management
  - tree_management_graveyard
  - udig
  - uomo
  - usssdk
  - wakaama
  - web_tools
  - webextensions
  - webtools
  - wtp_servertools
  - wtp_source_editing
  - xtend
  D:
  - spark
  - flink
  - flex
  - hbase
  - hive
  - ignite
  - ambari
  - camel
  - cassandra
  - kafka
  - arrow
  - solr
  - hadoop
  - hdfs
  - nifi
  - hdds
  - impala
  - beam
  - cb
  - ofbiz
  - sling
  - oak
  - yarn
  - groovy
  - lucene
  - geode
  - mesos
  - hudi
  - cxf
  - qpid
  - drill
  - amq
  - karaf
  - phoenix
  - calcite
  - mng
  - mapreduce
  - derby
  - wicket
  - felix
  - harmony
  - uima
  - zeppelin
  - iotdb
  - netbeans
  - pdfbox
  - axis2
  - thrift
  - kylin
  - artemis
  - ww
  - ranger
  - pig
  - atlas
  - sm
  - ts
  - jcr
  - zookeeper
  - accumulo
  - tika
  - tez
  - svn
  - bigtop
  - myfaces
  - carbondata
  - avro
  - tomee
  - james
  - storm
  - tuscany
  - causeway
  - systemds
  - asterixdb
  - airavata
  - oozie
  - log4j2
  - kudu
  - flume
  - trafodion
  - fop
  - couchdb
  - knox
  - tinkerpop
  - yunikorn
  - sqoop
  - hop
  - nutch
  - daffodil
  - str
  - openjpa
  - axis
  - proton
  - cay
  - scb
  - tap5
  - openmeetings
  - samza
  - minificpp
  - continuum
  - sentry
  - trinidad
  - fineract
  - tapestry
  - tobago
  - parquet
  - ratis
  - dispatch
  - cocoon
  - jena
  - metron
  - falcon
  - dirserver
  - httpclient
  - celeborn
  - surefire
  - xercesc
  - gobblin
  - guacamole
  - mahout
  - aries
  - tajo
  - orc
  - rol
  - reef
  - openejb
  - apexmalhar
  - mrm
  - shindig
  - aurora
  - syncope
  - smx4
  - hawq
  - datalab
  - xercesj
  - lang
  - connectors
  - opennlp
  - axis2c
  - tomahawk
  - math
  - stratos
  - ivy
  - olingo
  - jclouds
  - madlib
  - stanbol
  - lens
  - mshared
  - owb
  - submarine
  - mxnet
  - batik
  - deltaspike
  - js2
  - sshd
  - usergrid
  - dirstudio
  - rave
  - slider
  - giraph
  - yetus
  - for
  - beehive
  - dirmina
  - jspwiki
  - vcl
  - mrelease
  - synapse
  - xw
  - cmis
  - eagle
  - bookkeeper
  - axiscpp
  - ode
  - clerezza
  - taverna
  - stdcxx
  - libcloud
  - pivot
  - oodt
  - juddi
  - massembly
  - scm
  - hama
  - smxcomp
  - climate
  - xalanj
  - mdep
  - livy
  - velocity
  - unomi
  - msite
  - shiro
  - io
  - helix
  - vfs
  - jdo
  - configuration
  - mnemonic
  - jcrvlt
  - collections
  - chukwa
  - xalanc
  - mjavadoc
  - geronimodevtools
  - pluto
  - clk
  - inlong
  - apexcore
  - geronimo
  - ibatis
  - httpcore
  - dirkrb
  - whirr
  - sedona
  - buildr
  - net
  - curator
  - meclipse
  - compress
  - wss
  - legal
  - mresolver
  - doxia
  - crunch
  - log4net
  - streams
  - weex
  - marmotta
  - gora
  - amqcpp
  - xmlbeans
  - amqnet
  - lucenenet
  - hcatalog
  - archetype
  - streampipes
  - brooklyn
  - npanday
  - sis
  - qpidjms
  - wagon
  - dbcp
  - xap
  - dtacloud
  - mcompiler
  - tiles
  - beanutils
  - any23
  - singa
  - toree
  - js1
  - ctakes
  - logcxx
  - tc
  - rat
  - rya
  - ace
  - mplugin
  - nlpcraft
  - sdap
  - axiom
  - ftpserver
  - menforcer
  - validator
  - shale
  - mngsite
  - nemo
  - empiredb
  - odftoolkit
  - mshade
  - daemon
  - mpom
  - celix
  - river
  - mchanges
  - flagon
  - mpir
  - jexl
  - mwar
  - rampart
  - blur
  - edgent
  - wave
  - mcheckstyle
  - wink
  - aria
  - johnzon
  - wookie
  - whimsy
  - casssidecar
  - tamaya
  - pool
  - mailbox
  - aplo
  - mpmd
  - dirapi
  - htrace
  - metamodel
  - ivyde
  - rocketmq
  - imaging
  - griffin
  - torqueold
  - esme
  - torque
  - minvoker
  - gearpump
  - fileupload
  - bcel
  - cli
  - fincn
  - imap
  - labs
  - plc4x
  - vysper
  - doxiasitetools
  - joshua
  - meecrowave
  - fc
  - xbean
  - mime4j
  - codec
  - gsoc
  - nifireg
  - myriad
  - bahir
  - omid
  - mtomcat
  - lucy
  - mear
  - hivemall
  - smx4nmr
  - csv
  - extcdi
  - muse
  - tephra
  - abdera
  - polygene
  - spot
  - ibatisnet
  - mjar
  - mdeploy
  - etch
  - comdev
  - jelly
  - scxml
  - ddlutils
  - mresources
  - dosgi
  - netbeansinfra
  - jira_incubator
  - cactus
  - twill
  - smx4knl
  - sandbox
  - juneau
  - ognl
  - s2graph
  - fediz
  - modpython
  - mindexer
  - mskins
  - santuario
  - attic
  - manttasks
  - awf
  - log4php
  - podlingnamesearch
  - vxquery
  - woden
  - jcs
  - minifi
  - portletbridge
  - freemarker
  - text
  - dir
  - mrunit
  - oltu
  - sandesha2
  - pio
  - dl
  - hivemind
  - mantrun
  - veltools
  - email
  - mph
  - numbers
  - serf
  - jxpath
  - dmap
  - minstall
  - openoffice
  - digester
  - batchee
  - wscommons
  - bval
  - logging
  - xmlrpc
  - jxr
  - rng
  - extscript
  - datafu
  - s4
  - droids
  - soap
  - crypto
  - gump
  - mailet
  - extval
  - rampartc
  - mwrapper
  - commonssite
  - olio
  - dbutils
  - mrresources
  - geometry
  - mchangelog
  - dubbo
  - mgpg
  - ojb
  - xgc
  - msources
  - cassanalytics
  - directmemory
  - qpidit
  - httpasync
  - scout
  - cocoon3
  - stonehenge
  - quickstep
  - mejb
  - mbuildcache
  - exec
  - zetacomp
  - cassjava
  - clownfish
  - dirshared
  - protocols
  - mclean
  - onami
  - hupa
  - jsieve
  - jspf
  - pb
  - crail
  - chain
  - cassgo
  - grft
  - wsrp4j
  - mpdf
  - ripple
  - jaxme
  - hise
  - trb
  - mrql
  - gossip
  - liminal
  - age2
  - xmlcommons
  - photark
  - httpdraft
  - scimple
  - wsif
  - mplugintesting
  - mjlink
  - mrar
  - amaterasu
  - steve
  - martifact
  - samoa
  - statistics
  - pirk
  - apa
  - jci
  - commonsrdf
  - marvin
  - marchetypes
  - mant
  - doxiatools
  - easyant
  - sandesha2c
  - betwixt
  - mjarsigner
  - mynewtdoc
  - ocm
  - myfacestest
  - mscmpub
  - pylucene
  - xmlschema
  - daytrader
  - orchestra
  - mdoap
  - sirona
  - ageold
  - hdt
  - cloudstack
  - tst
  - masfres
  - mtoolchains
  - horn
  - pnix
  - jcrsite
  - macr
  - wayang
  - kalumet
  - xercesp
  - dormant
  - cor
  - runtime
  - exlbr
  - apollo
  - chainsaw
  - cxfxjc
  - jdkim
  - mavibot
  - clke
  - provisionr
  - bsf
  - mfcommons
  - asyncweb
  - agila
  - mpt
  - iota
  - transaction
  - training
  - resources
  - mlinkcheck
  - mverifier
  - apisix
  - mrepository
  - milagro
  - addr
  - oep
  - di
  - mdocck
  - imperius
  - jcrrmi
  - kitty
  - whisker
  - mjmod
  - modeler
  - mjdeps
  - tuweni
  - functor
  - openwire
  - mstage
  - proxy
  - tashi
  - weaver
  - portals
  - nuttx
  - gbuild
  - tentacles
  - postage
  - openaz
  - nuvem
  - pulsar
  - autotag
  - asfsite
  - concerted
  - coral
  - fortress
  - neethi
  - prc
  - nip
  - sb
  - site
  - discovery
  - mfhtml5
  - treq
  - tilesshared
  - el
  - cmda
  - echarts
  - central
  - jcrtck
  - mpatch
  - texen
  - mscripting
  - sand
  - casspython
  - pinot
  - studio
  - kato
  - hermes
  - superset
  - cotton
  - dirnaming
  - tilesshow
  - jira_testing
  - dirtsec
  - amqcli
  - alois
  - datasketches
  - cs
  - attributes
  - primitives
  - dbf
  - mjdeprscan
  - orp
  - savan
  - brand
  - launcher
  - pegasus
  - wadi
  - bluesky
  - kand
  - lcn4c
  - tilessb
  - blaze
  - bluemarlin
  - eventmesh
  - feedparser
  - dirgroovy
  - jacob
  - velocitysb
  - anakia
  - ews
  - lokahi
  - mirae
  - avalon
  - armi
  - casscpp
  - avnsharp
  - jcrservlet
  - owc
  - triples
  - acl
  - transports
  - tm
  - heraldry
  - tatpi
  - doris
  - gluten
  - ecs
  - nifilibs
  - amqwebsite
  - cassnodejs
  - otava
  - jira_tools
  - jcrbench
  - jcrcl
  - depot
  - dvsl
  - escimo
  - rbatis
  - stomp
  - tsik
  - aar
  - cloudberry
  - mcfsdk
  - zipkin
  - planet
  - gavtesty
  - infratesty33
  - ki
  - mynewt
  - mmetric
  - teval
